name: 'job-b'

on:
  workflow_call:

jobs:
  job-b:
    name: "Teams notification"
    runs-on: [self-hosted,Linux,X64]
    steps:
    - name: "Checking CI/CD Result"
    - uses: actions/checkout@v3

    - name: "Run job-b"
      shell: bash
      run: |
        echo "Hello job-b"
