name: 'job-c'

on:
  workflow_call:

jobs:
  job-c:
    name: "job-c"
    runs-on: [self-hosted,Linux,X64]
    steps:
    - uses: actions/checkout@v3

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        path: artifacts
        name: artifacts

    - name: "Run job-c"
      shell: bash
      run: |
        echo "Hello job-c"
        mkdir artifacts
        echo "Hello job-c" > artifacts/job-c.txt

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        path: artifacts
        name: artifacts

