name: 'job-c'

on:
  workflow_call:

jobs:
  job-c:
    name: "job-c"
    runs-on: [self-hosted,Linux,X64]
    steps:
    - uses: actions/checkout@v3

    - name: "Run job-c"
      shell: bash
      run: |
        echo "Hello job-c"
